### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [dgryski/go-bloomindex#4]
@dgryski what would be the license for your code? Thanks!

**Comment by dgryski** [comment]
I'll put MIT on it. Are you using this code? I'd love to know how, if so.

**Comment by pombredanne** [comment]
@dgryski Thank you ++ for the quick reply!
> Are you using this code? I'd love to know how, if so.

not yet, but considering to... I would not have moved ahead before I knew it was licensed alright ;)
I will keep you posted!
